# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='extended_price_per_product',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price_per_product',
        ),
        migrations.RemoveField(
            model_name='project',
            name='products',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quantity_per_product',
        ),
    ]
