# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyquantity',
            name='subassembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='assemblyquantity',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Part'),
        ),
    ]
