# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_files', verbose_name='Part Image'),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_files', verbose_name='Part Image'),
        ),
    ]
