# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
