# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160722_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyquantity',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assembly'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='products',
        ),
        migrations.AddField(
            model_name='project',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assembly'),
        ),
    ]
