# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160724_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cad_file',
            field=models.FileField(blank=True, null=True, upload_to='cad_files'),
        ),
    ]
