# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160725_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_assembly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assembly')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
    ]
