# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160731_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyquantity',
            name='cost',
        ),
    ]
